
version: '3'
services:
  webdav:
    image: bytemark/webdav
    hostname: webdav
    restart: always
    environment:
      AUTH_TYPE: Digest
      USERNAME: frodo
      PASSWORD: bolson
    volumes:
      - /docker/files:/var/lib/dav

  nginx:
    image: nginx:latest
    container_name: proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80